### ISSUE TITLE
feat: implement combined metric

### ISSUE THREAD

**Issue by subhankarb** [waterdipai/datachecks#46]
## **Tell us about the problem you're trying to solve**

As a user, I want to generate combined metrics.

## **Describe the solution you’d like**
Combined metric is a special type of metric, which will be generated with a combination of two defined metrics. Below are examples of two combined metric

```
metrics:
  - name: count_us_parts
    metric_type: document_count
    resource: search_datastore.product_data_us
  - name: count_us_parts_valid
    metric_type: row_count
    resource: product_db.products
```

```
- name: combined_metric_example
  metric_type: combined
  expression: sum(count_us_parts, count_us_parts_valid)
```
```
- name: combined_metric_example
  metric_type: combined
  expression: div(sum(count_us_parts, count_us_parts_valid), count_us_parts_not_valid)
```

```
- name: combined_metric_example_percentage
  metric_type: combined
  expression: mul(div(count_us_parts, count_us_parts_valid), 100)
```

### Available Functions:

- `div()`
- `sum()`
- `mul()`
- `sub()`

## Tasks:

- [ ] Extract functions from the expression string.
- [ ] Define a Combined metric class to calculate the metric
- [ ] Configuration extraction for combined metrics
